config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  namespace :ajax do
    resources :cities, only: :index
  end

  namespace :admin do
    resources :file_uploads
    get '/' => 'file_uploads#index'
  end

  resources :select_country_and_city, only: :index
  root to: 'select_country_and_city#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :country
end

app/models/country.rb
class Country < ApplicationRecord
  validates :name, presence: true
  has_many :cities, dependent: :destroy

  def country_name
    ISO3166::Country[name].to_s
  end
end

app/models/file_upload.rb
class FileUpload < ApplicationRecord
  include AttachmentUploader::Attachment(:attachment)
  enum status: { pending: 0, uploading: 1, uploaded: 2 }
end

app/controllers/admin/base_controller.rb
# frozen_string_literal: true

module Admin
  class BaseController < ApplicationController
    layout 'admin/base'
  end
end

app/controllers/admin/file_uploads_controller.rb
# frozen_string_literal: true

module Admin
  class FileUploadsController < Admin::BaseController
    def index
      @file_uploads = FileUpload.all.order(created_at: :desc)
    end

    def new
      @file_upload = FileUpload.new
    end

    def create
      @file_upload_service = ::FileUploadService.new(file_upload_params)
      if @file_upload_service.valid?
        @file_upload_service.save!
        redirect_to [:admin, :file_uploads], notice: 'File successfully uploaded.'
      else
        redirect_to [:new, :admin, :file_upload], alert: 'File failed to upload.'
      end
    end

    private

    def file_upload_params
      params.require(:file_upload).permit(:attachment)
    end
  end
end

app/controllers/ajax/cities_controller.rb
module Ajax
  class CitiesController < ActionController::Base
    def index
      country = Country.find_by_name(params[:country])
      cities = country ? country.cities.order(name: :asc).collect(&:name).unshift('') : ['']
      render json: cities
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/select_country_and_city_controller.rb
class SelectCountryAndCityController < ApplicationController
  def index
    @countries = Country.all.order(name: :asc)

    if params[:country].present? && params[:city].present?
      client_country_code = Geocoder.search(request.remote_ip).first.country

      if client_country_code.present? && client_country_code != params[:country]
        flash[:notice] = "Hey it looks like you are from #{ISO3166::Country[client_country_code]}."
      else
        flash[:notice] = "Hello from #{ISO3166::Country[params[:country]]}, #{params[:city]}."
      end
    end
  end
end

app/helpers/application_helper.rb
#:nocov:
module ApplicationHelper
end
#:nocov:

app/views/admin/file_uploads/index.html.erb
<div class="row">
  <div class="col">
    <h1>File Uploads</h1>
  </div>
  <div class="col-auto">
    <%= link_to 'New File Upload', [:new, :admin, :file_upload], class: 'btn btn-primary' %>
  </div>
</div>

<table class="table">
  <thead>
    <tr>
      <th>Id</th>
      <th>Created</th>
      <th>Status</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <% @file_uploads.each do |file_upload| %>
        <tr>
          <td><%= file_upload.id %></td>
          <td><%= file_upload.created_at %></td>
          <td><%= file_upload.status.humanize %></td>
        </tr>
      <% end %>
    </tr>
  </tbody>
</table>

app/views/admin/file_uploads/new.html.erb
<div class="row">
  <div class="col">
    <h1>New File Upload</h1>
  </div>
  <div class="col-auto">
    <%= link_to 'Back', [:admin, :file_uploads], class: 'btn btn-secondary' %>
  </div>
</div>

<%= form_with model: [:admin, @file_upload], multipart: true, local: true do |f| %>
  <%= f.file_field :attachment %>

  <div class="text-right">
    <%= f.submit 'Save', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
  <%= link_to 'Countries And Cities', root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
</nav>

app/views/layouts/admin/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
  <%= link_to 'Countries And Cities', admin_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <div class='text-white text-right ml-auto'>
      Welcome Admin
    </div>
  </div>
</nav>

app/views/layouts/admin/base.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CountriesAndCities</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/admin/navbar' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CountriesAndCities</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <% flash.each do |name, msg| %>
        <div class="alert alert-primary" role="alert">
          <%= msg %>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/select_country_and_city/index.html.erb
<%= form_with url: "/", method: "get", data: { country_and_city_form: '' }, local: true do %>
  <h2>Select Country</h2>

  <div class="row mb-4">
    <div class="col-12 col-lg-4">
      <%= select_tag :country, options_for_select(@countries.collect { |country| [country.country_name, country.name] }), include_blank: true, data: { country_select: '' }, style: 'width: 100%' %>
    </div>
  </div>

  <h2>Select City</h2>

  <div class="row mb-4">
    <div class="col-12 col-lg-4">
      <%= select_tag :city, options_for_select([]), include_blank: true, data: { city_select: '' }, style: 'width: 100%' %>
    </div>
  </div>

  <%= submit_tag "Submit", class: 'btn btn-primary d-block', disabled: true %>
<% end %>